services:

  mariadb:
    image: mariadb:latest
    container_name: mariadb-data
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=albums
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=docker
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
      image: minio/minio
      container_name: minio
      environment:
        MINIO_ACCESS_KEY: minioadmin
        MINIO_SECRET_KEY: minio@1234!
      ports:
        - "9000:9000"
        - "9001:9001"
      command: server /data --console-address ":9001"
      volumes:
        - minio_data:/data
   
  minio_mc:
      image: minio/mc
      container_name: minio_mc
      depends_on:
        - minio
      entrypoint: |
        sh -c "
        sleep 10 &&
        mc alias set myminio http://minio:9000 minioadmin minio@1234! &&
        mc mb myminio/landing
        "

  postgres-airflow:
    image: postgres:15
    container_name: postgres-airflow
    environment:
      POSTGRES_USER: post_airflow
      POSTGRES_PASSWORD: airflow_123
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  
  airflow:
    build:
      context: .
      dockerfile: airflow/config_airflow/airflow.Dockerfile
    container_name: airflow
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://post_airflow:airflow_123@postgres-airflow:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: 'False'
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
      AIRFLOW__CORE__LOGGING_LEVEL: INFO
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minio@1234!
    depends_on:
      - postgres-airflow
      - mariadb
      - minio
    ports:
      - "8080:8080" 
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/config_airflow:/opt/airflow/config_airflow
  
    command: ['airflow', 'standalone']

  postgres-superset:
    image: postgres:15
    container_name: postgres-superset
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: superset
    ports:
      - "5433:5432"  # Alterando a porta externa para evitar conflito
    volumes:
      - superset_pgdata:/var/lib/postgresql/data

 
  superset:
    build: 
      context: ./superset
      dockerfile: superset.Dockerfile
    container_name: superset
    ports:
      - 8088:8088
    environment:
      ADMIN_USERNAME: admin
      ADMIN_FIRSTNAME: Admin
      ADMIN_LASTNAME: User
      ADMIN_EMAIL: admin@superset.com
      ADMIN_PASSWORD: admin123
      SUPERSET_SECRET_KEY: mysecretkey
      SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://admin:admin@postgres-superset:5432/superset
    depends_on:
      - postgres-superset
    volumes:
      - superset_home:/app/superset_home

volumes:
  postgres_data:
  minio_data:
  mariadb_data:
  superset_pgdata:
  superset_home:
